# Generated by Django 4.0.6 on 2022-07-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_professionalprofile_remove_worker_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='professional_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.professionalprofile'),
        ),
        migrations.AddField(
            model_name='worker',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization'),
        ),
    ]
