# Generated by Django 4.0.6 on 2022-07-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_worker_professional_profile_worker_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Профессиональный профиль'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=models.ForeignKey(limit_choices_to=models.Q(('specialization__professional_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.professionalprofile'))), null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization'),
        ),
    ]
