# Generated by Django 4.0.6 on 2022-07-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_worker_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=models.ForeignKey(limit_choices_to=models.Q(('professional_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.professionalprofile'))), null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization'),
        ),
    ]
