# Generated by Django 4.0.6 on 2022-07-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_worker_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization'),
        ),
    ]
