# Generated by Django 4.0.6 on 2022-07-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_locationworktime_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='finish_work_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.location'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='start_work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
