# Generated by Django 4.0.6 on 2022-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='finish_work_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_work_time',
            field=models.TimeField(),
        ),
    ]
