# Generated by Django 4.0.6 on 2022-07-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_alter_locationworktime_finish_break_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('procedure_duration', models.DurationField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
    ]
