# Generated by Django 4.0.6 on 2022-07-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_alter_procedure_procedure_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization', verbose_name='Специализация'),
        ),
    ]
