# Generated by Django 4.0.6 on 2022-07-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_procedure_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.location')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.procedure')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.worker')),
            ],
        ),
    ]
