# Generated by Django 4.0.6 on 2022-07-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.procedure', verbose_name='Процедура'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.worker', verbose_name='Ф.И.О. специалиста'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='day_week',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='finish_break_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Перерыв до'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='finish_work_time',
            field=models.TimeField(verbose_name='Окончание рабочего дня'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='start_break_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Перерыв с'),
        ),
        migrations.AlterField(
            model_name='locationworktime',
            name='start_work_time',
            field=models.TimeField(verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Процедура'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_duration',
            field=models.IntegerField(verbose_name='Длительность процедуры в мин'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finish_work_time',
            field=models.TimeField(verbose_name='Конец рабочего периода'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_work_time',
            field=models.TimeField(verbose_name='Начало рабочего периода'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.worker', verbose_name='Ф.И.О.'),
        ),
    ]
