# Generated by Django 4.0.6 on 2022-07-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_delete_appointment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField(verbose_name='Время записи')),
                ('client_name', models.CharField(max_length=255, verbose_name='Ф.И.О. клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('client_email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.procedure', verbose_name='Процедура')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.schedule')),
            ],
        ),
    ]
