# Generated by Django 4.0.6 on 2022-07-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_rename_procedure_duration_procedure_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment2',
            name='appointment_time',
            field=models.TimeField(blank=True, verbose_name='Время записи'),
        ),
    ]
