# Generated by Django 4.0.6 on 2022-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_alter_appointment2_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment2',
            name='appointment_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время записи'),
        ),
    ]
