# Generated by Django 4.0.6 on 2022-07-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_delete_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment2',
            new_name='Appointment',
        ),
    ]
